name: Deploy Storefront
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key:  ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run:  |
          npm i
          npx nx build storefront --prod
          cp tools/docker/storefront/Dockerfile dist/apps/storefront/Dockerfile
          cp tools/docker/storefront/nginx.conf.template dist/apps/storefront/nginx.conf.template
          echo ${{secrets.DOCKER_HUB_ACCESS_TOKEN}} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          cd dist/apps/storefront
          docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/tcode-storefront:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/tcode-storefront
